<template>
  <DropdownMenu>
    <DropdownMenuTrigger as-child>
      <button class="lang-trigger" :class="{ 'icon-only': collapsed }">
        <Languages :size="16" />
        <span v-if="!collapsed" class="lang-text">{{ currentLangText }}</span>
      </button>
    </DropdownMenuTrigger>
    <DropdownMenuContent>
      <DropdownMenuItem :disabled="currentLang === 'zh-CN'" @click="handleCommand('zh-CN')">
        简体中文
      </DropdownMenuItem>
      <DropdownMenuItem :disabled="currentLang === 'en-US'" @click="handleCommand('en-US')">
        English
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Languages } from 'lucide-vue-next'

defineProps<{ collapsed?: boolean }>()
import { useI18n } from 'vue-i18n'
import { setLanguage } from '@/locales'
import { toast } from 'vue-sonner'
import { settingsAPI } from '@/api/settings'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'

const { locale } = useI18n()

const currentLang = ref(locale.value)
const loading = ref(false)

const currentLangText = computed(() => {
  return currentLang.value === 'zh-CN' ? '中文' : 'English'
})

const handleCommand = async (lang: string) => {
  if (loading.value) return

  const backendLang = lang === 'zh-CN' ? 'zh' : 'en'
  const currentBackendLang = currentLang.value === 'zh-CN' ? 'zh' : 'en'

  const confirmMessage = backendLang === 'zh'
    ? `切换为中文后，后端生成的所有提示词、角色描述、场景描述等都将使用中文。是否继续？


After switching to Chinese, all prompts, character descriptions, scene descriptions generated by the backend will use Chinese. Continue?`
    : `After switching to English, all prompts, character descriptions, scene descriptions generated by the backend will use English. Continue?


切换为英文后，后端生成的所有提示词、角色描述、场景描述等都将使用英文。是否继续？`

  if (!window.confirm(confirmMessage)) return

  loading.value = true
  try {
    const res = await settingsAPI.updateLanguage(backendLang)
    setLanguage(lang)
    currentLang.value = lang
    toast.success(res?.message || (backendLang === 'zh' ? '语言已切换为中文' : 'Language switched to English'))
  } catch (error: any) {
    console.error('Failed to switch language:', error)
    let errorMessage = '未知错误'
    if (error?.message) errorMessage = error.message
    else if (error?.response?.data?.error?.message) errorMessage = error.response.data.error.message
    else if (typeof error === 'string') errorMessage = error
    const errorMsg = currentBackendLang === 'zh'
      ? `切换语言失败: ${errorMessage}`
      : `Failed to switch language: ${errorMessage}`
    toast.error(errorMsg)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.lang-trigger {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  height: 36px;
  padding: 0 10px;
  border: 1px solid var(--border-primary);
  border-radius: var(--radius-md);
  background: var(--bg-card);
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 150ms;
  white-space: nowrap;
  font-size: 13px;
}

.lang-trigger.icon-only {
  width: 36px;
  padding: 0;
}

.lang-trigger:hover {
  background: var(--bg-card-hover);
  color: var(--text-primary);
  border-color: var(--border-secondary);
}

.lang-trigger:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

.lang-text {
  color: inherit;
}
</style>
